version: "3.9"

volumes:
  cert:
  mysql-store:
    driver: local
  minio:

services:
  web:
    build: ./web
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
    volumes:
      - ./src:/var/www/html
      - ./web/logs:/var/log/httpd
      - cert:/etc/ssl/private
    restart: always
    env_file: .env

  php:
    build: ./php
    depends_on:
      - db
      - minio
    ports:
      - 9000
    volumes:
      - ./src:/var/www/html
    restart: always
    env_file: .env

  db:
    build: ./db
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./db/logs:/var/log/mysql
      - mysql-store:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    env_file: .env
    ports:
      - 8080:80
    restart: always

  composer:
    image: composer

  node:
    image: node
    tty: true
    ports:
      - '8081'
    depends_on:
      - web
    volumes:
      - ./src:/var/www/html
    restart: always

  maildev:
    image: djfarrelly/maildev
    ports:
      - 8082:80
    restart: always

  minio:
    image: minio/minio
    ports:
      - 8083:9000
    volumes:
      - minio:/export
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /export
    restart: always
